import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
        <button
          onClick={() => router.push("/form/home")}
          style={{ fontSize: '100px', width: '500px', margin: '50px' }}
        >Go Form!</button>
        <button
          onClick={() => router.push("/rsp/home")}
          style={{ fontSize: '100px', width: '500px', margin: '50px'  }}
        >Go Rsp!</button>
      </div>
    </div>
  )
}
